### ISSUE TITLE
basic_materials mod cannot enabled and no optional dependencies 

### ISSUE THREAD

**Issue by TYAGAGerson** [mt-mods/basic_materials#2]
mostly there are default dependencies and moreores (optional)
the image:
![image](https://user-images.githubusercontent.com/96607422/147318300-dcaaa599-d4a0-4206-8938-6931a44e2676.png)

**Comment by wsor4035** [comment]
i have had this exact issue, i can see you have <https://github.com/joe7575/techage_modepack> installed (techage modpack) which contains basic_materials, and minetest gui is dumb and will try and force enable the one from the modpack rather than the one in /mods. should be resolved by https://github.com/minetest/minetest/pull/11784

**Comment by TYAGAGerson** [comment]
oh, thanks. Yeah, I force to enable basic materials mod by editing the world.mt on my minetest world.
![image](https://user-images.githubusercontent.com/96607422/147322530-fdae4d29-444d-4aa7-b9fe-148dc787c2d4.png)

**Comment by TYAGAGerson** [comment]
i will move the techage modpack.
